title: Coderic Development Team
email: admin@coderic.net
description: Sómos una comunidad de desarrolladores, que trabajamos de forma colaborativa en los ecosistemas tecnológicos de Coderic, S.A.
baseurl: ""
url: "https://dev.coderic.net"
google_analytics: UA-628256-9
author: Coderic
logo: /images/logo43.png
lang: es
markdown: kramdown
include: [_redirects, _headers]
remote_theme: Coderic/coderic-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
