title: Coderic Development Team
email: info@coderic.co.ve
description: Corporacion Orientada al Desarrollo Estratégico de Recursos de Información Comercial
baseurl: ""
url: "https://dev.coderic.co.ve"
disqus: coderic
google_analytics: UA-628256-8
facebook:
    app_id: 
    version: v3.2
author: Coderic
logo: /images/logo43.png
lang: es
markdown: kramdown
include: [_redirects, _headers]
remote_theme: Coderic/coderic-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate