title: Coderic Development Team
email: info@coderic.co.ve
description: Corporacion Orientada al Desarrollo Estratégico de Recursos de Información Comercial
baseurl: ""
url: "https://dev.coderic.co.ve"
twitter_username: CodericDev
github_username:  CodericDev
author: Coderic
logo: /images/logo43.png
lang: es
markdown: kramdown
remote_theme: Coderic/coderic-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate